/**
 * The generated-face dependency gate: which imports count, which manifests
 * declare them, and that the shipped tree generates a corpus large enough for a
 * clean result to mean something.
 */
import { describe, expect, it } from 'vitest'
import {
  collectFaceImports,
  declaredPackages,
  declaresHostFace,
  findFaceDependencyViolations,
  owningPackage,
  scanRepository,
  type GeneratedFace,
} from './verify-typert-face-dependencies.ts'

/**
 * Build manifest facts for one package.
 * @param name - package name.
 * @param sections - declared dependency sections.
 * @returns package facts the violation check consumes.
 */
function facePackage(name: string, sections: Record<string, Record<string, string>>) {
  const manifest = { name, ...sections }
  return {
    name,
    dir: `packages/host/${name}`,
    manifestPath: `packages/host/${name}/package.json`,
    declared: declaredPackages(manifest),
  }
}

/**
 * Build one generated face.
 * @param name - owning package name.
 * @param js - emitted module source.
 * @returns the face the violation check consumes.
 */
function face(name: string, js: string): GeneratedFace {
  return { package: name, packageRoot: `packages/host/${name}`, js }
}

describe('manifest facts', () => {
  it('merges dependencies, peer dependencies, and optional dependencies', () => {
    expect([...declaredPackages({
      dependencies: { zod: '^4.4.3' },
      peerDependencies: { '@qilin/kylin': 'workspace:~' },
      optionalDependencies: { chokidar: '^4.0.0' },
      devDependencies: { vitest: '^3.0.0' },
    })].sort()).toEqual(['@qilin/kylin', 'chokidar', 'zod'])
  })

  it('admits the generated Host entry and excludes the Client remote entry', () => {
    expect(declaresHostFace({ exports: { './typert': { types: './lib/typert.host.d.ts', default: './lib/typert.host.js' } } })).toBe(true)
    expect(declaresHostFace({ exports: { './remote': { types: './lib/typert.remote-client.d.ts', default: './lib/typert.remote-client.js' } } })).toBe(false)
    expect(declaresHostFace({})).toBe(false)
  })
})

describe('face imports', () => {
  it('reads the value import the generator emits, with its line', () => {
    expect(collectFaceImports("/* Generated by @qilin/typert-generator from FaceModel — do not edit. */\nimport { z } from 'zod'\n"))
      .toEqual([{ specifier: 'zod', line: 2 }])
  })

  it('reads scoped and deep specifiers as their package name', () => {
    expect(collectFaceImports("import { a } from '@qilin/typert-protocol'\nimport { b } from '@qilin/kylin/dist/x.js'\n").map(entry => entry.specifier))
      .toEqual(['@qilin/typert-protocol', '@qilin/kylin/dist/x.js'])
  })

  it('excludes relative specifiers and builtins, which no manifest declares', () => {
    expect(collectFaceImports("import { a } from './impl.js'\nimport { b } from '../shared.js'\nimport { c } from 'node:fs'\n")).toEqual([])
  })

  it('excludes a dynamic import and a bare string that is not an import statement', () => {
    expect(collectFaceImports("const s = \"import { z } from 'zod'\"\nawait import('chokidar')\n")).toEqual([])
  })
})

describe('owning package', () => {
  it('reduces scoped, unscoped, and deep specifiers to the package that owns them', () => {
    expect(owningPackage('zod')).toBe('zod')
    expect(owningPackage('react-dom')).toBe('react-dom')
    expect(owningPackage('chokidar/x.js')).toBe('chokidar')
    expect(owningPackage('@qilin/kylin')).toBe('@qilin/kylin')
    expect(owningPackage('@qilin/kylin/dist/x.js')).toBe('@qilin/kylin')
  })

  it('keeps a scope-only specifier whole instead of slicing past its end', () => {
    expect(owningPackage('@scope')).toBe('@scope')
  })
})

describe('undeclared imports', () => {
  it('rejects the omission that stalled the whole contributor batch at boot', () => {
    const violations = findFaceDependencyViolations(
      [face('sidebar-opens', "import { z } from 'zod'\n")],
      new Map([['sidebar-opens', facePackage('sidebar-opens', { dependencies: { '@qilin/schemastery': 'workspace:~' } })]]),
    )
    expect(violations).toEqual([{
      package: 'sidebar-opens',
      specifier: 'zod',
      line: 1,
      packageRoot: 'packages/host/sidebar-opens',
      manifestPath: 'packages/host/sidebar-opens/package.json',
    }])
  })

  it('admits the same import once the manifest declares it', () => {
    expect(findFaceDependencyViolations(
      [face('sidebar-opens', "import { z } from 'zod'\n")],
      new Map([['sidebar-opens', facePackage('sidebar-opens', { dependencies: { zod: '^4.4.3' } })]]),
    )).toEqual([])
  })

  it('admits a workspace package declared as a peer dependency', () => {
    expect(findFaceDependencyViolations(
      [face('plugin-inventory', "import { TypertProtocol } from '@qilin/typert-protocol'\n")],
      new Map([['plugin-inventory', facePackage('plugin-inventory', { peerDependencies: { '@qilin/typert-protocol': 'workspace:*' } })]]),
    )).toEqual([])
  })

  it('fails loud when a generated face has no manifest facts', () => {
    expect(() => findFaceDependencyViolations([face('unknown', "import { z } from 'zod'\n")], new Map()))
      .toThrow(/unknown package/)
  })
})

describe('shipped tree', () => {
  it('generates a corpus large enough to mean something, and declares every import', () => {
    const { violations, faces } = scanRepository()
    expect(faces).toBeGreaterThanOrEqual(20)
    expect(violations).toEqual([])
  }, 120_000)
})
